In [2]:
import numpy as np

In [ ]:
def isDiagonallyDominant(A):
    for i in range(A.shape[0]):
        if abs(A[i, i]) < np.sum(abs(A[i, :])) - abs(A[i, i]):
            return False
    return True

In [35]:
# returns the spectral radius of a matrix
def spectral_radius(A:np.array):
    if A.shape[0] != A.shape[1]:
        raise ValueError("Matrix must be square")
    return np.max(np.abs(np.linalg.eigvals(A)))

In [53]:
A = np.array([[6, 0, 7, 10], [1, 11, 7, 6], [3, 7, 4, 1], [9, 13, 5, 2]], dtype=np.float64)
for i in range(A.shape[0]):
     A[i,:] = (A[i,:] / A[i,i])
print(A)
spectral_radius(A)

[[1.         0.         1.16666667 1.66666667]
 [0.09090909 1.         0.63636364 0.54545455]
 [0.75       1.75       1.         0.25      ]
 [4.5        6.5        2.5        1.        ]]


4.98698373947921

In [6]:
#Jacobi Iteration
def JacobiIteration(A: np.array, b:np.array, tol:float = 1e-10, maxIter:int = 1000):
    A = np.array(A, dtype=np.float64)
    x = np.zeros_like(b, dtype=np.float64) #initial guess
    T = A - np.diag(np.diag(A)) #T = A - D
    for k in range(maxIter):
        x_old = x.copy()
        x[:] = (b - np.dot(T, x)) / np.diag(A)
        if np.linalg.norm(x - x_old, np.inf) < tol:
            return x
    return x

In [9]:
A = np.array([[2, 1], [5, 7]])
b = np.array([11, 13])
A = np.array([[10, -1, 2, 0], [-1, 11, -1, 3], [2, -1, 10, -1], [0, 3, -1, 8]])
b = np.array([6, 25, -11, 15])
JacobiIteration(A, b)

array([ 1.,  2., -1.,  1.])

In [10]:
#Gauss-Seidel Iteration
def GaussSeidelIteration(A: np.array, b:np.array, tol:float = 1e-10, maxIter:int = 1000):
    A = np.array(A, dtype=np.float64)
    x = np.zeros_like(b, dtype=np.float64) #initial guess
    i = 0
    for k in range(maxIter):
        i += 1
        x_old = x.copy()
        for i in range(A.shape[0]):
            x[i] = (b[i] - np.dot(A[i, :i], x[:i]) - np.dot(A[i, i+1:], x_old[i+1:])) / A[i, i]
        if np.linalg.norm(x - x_old, np.inf) < tol:
            return x
    return x

In [11]:
A = np.array([[16, 3], [7, -11]])
b = np.array([11, 13])
GaussSeidelIteration(A, b)

array([ 0.81218274, -0.66497462])

In [ ]:
#Successive Over-Relaxation
def SOR():
    pass

In [ ]:
#Iterative Refinement
def IterativeRefinement():
    pass