In [5]:
import numpy as np

In [6]:
# Newton's Divided Difference
def dividedDifference(x, y):
    """
    Newton's divided difference algorithm.
    """
    n = len(x)
    coef = np.zeros((n,n))
    coef[:,0] = y
    for j in range(1,n):
        for i in range(n-j):
            coef[i][j] = (coef[i+1][j-1] - coef[i][j-1])/(x[i+j] - x[i])
    return coef

In [7]:
### Neville's Interpolation
def nevilleInterpolation(x, y, z):
    """
    Neville's method for interpolating a function y(x) at a point z.
    """
    n = len(x)
    if len(y) != n:
        raise ValueError("x and y must have the same length.")
    coef = np.zeros((n, n))
    coef[:, 0] = y
    for j in range(1, n):
        for i in range(j, n):
            coef[i, j] = ((z - x[i - j])*coef[i, j - 1] + (x[i] - z)*coef[i - 1, j - 1])/(x[i] - x[i - j])
    return coef

#### 1. Use appropriate Lagrange interpolating polynomials of degrees one, two, and three to approximate the following: $f (0.43)$ if $f (0) = 1, f (0.25) = 1.64872, f (0.5) = 2.71828,f (0.75) = 4.48169$.


##### $P_1(x) = \frac{x-x_1}{x_0-x_1}f(x_0) + \frac{x-x_0}{x_1-x_0}f(x_1)$
##### $x = 0.43, x_0 = f(0.25), x_1 = f(0.5)$
##### $\implies \frac{0.43-0.5}{0.25-0.5}f(0.25) + \frac{0.43 - 0.25}{0.5-0.25}f(0.5)$
##### $\implies 0.28 * 1.64872 + 0.72 * 2.71828$
##### $\implies f(0.43) = 2.41918$

#### $L_0, L_1, L_2$

#### $L_0(x) = \frac{(x-0.5)(x-0.75)}{(0.25-0.5)(0.25-0.75)}$
#### $= 8(x-0.5)(x-0.75)$
#### $L_1(x) = \frac{(x-0.25)(x-0.75)}{(0.5-0.25)(0.5-0.75)}$
#### $= -16(x-0.25)(x-0.75)$
#### $L_2(x) = \frac{(x-0.25)(x-0.5)}{(0.75-0.25)(0.75-0.5)}$
#### $= 8(x-0.25)(x-0.5)$
#### $L_0(0.43) + L_1(0.43) + L_2(0.43) = 2.34886$


#### $L_0,L_1,L_2,L_3$

#### $L_0(x) = \frac{(x-0.25)(x-0.5)(x-0.75)}{(0-0.25)(0-0.5)(0-0.75)}$
#### $= -\frac{32}{3}(x-0.25)(x-0.5)(x-0.75)$
#### $L_1(x) = \frac{(x-0)(x-0.5)(x-0.75)}{(0.25-0)(0.25-0.5)(0.25-0.75)}$
#### $= 32(x-0)(x-0.5)(x-0.75)$
#### $L_2(x) = \frac{(x-0)(x-0.25)(x-0.75)}{(0.5-0)(0.5-0.25)(0.5-0.75)}$
#### $= -32(x-0)(x-0.25)(x-0.75)$
#### $L_3(x) = \frac{(x-0)(x-0.25)(x-0.5)}{(0.75-0)(0.75-0.25)(0.75-0.5)}$
#### $= \frac{32}{3}(x-0)(x-0.25)(x-0.5)$
#### $L_0(0.43) + L_1(0.43) + L_2(0.43) + L_3(0.43) = 2.36060$


#### 2. The data for problem 3 (previous problem) were generated using the function $y = e^{2x}$. Use the error formula to find a bound for the error, and compare the bound to the actual error for the cases $n = 1$ and $n = 2$.

#### for  $n = 1$
#### $E \le \frac{f''(\epsilon(x))}{2!}(x-x_0)(x-x1)$
#### $\implies E \le \frac{4e^{2\epsilon(x)}}{2!}(x-0)(x-.25)$
#### $\implies E \le 2e^{2\epsilon(x)}(x)(x-0.25)$
#### $\implies E \le 2e^{2(.5)}(x^2 - 0.25x)$
#### $\implies E \le 0.68$

#### actual error 
#### $f(0.43) - e^{2*0.43}$
#### $= 1 + 2.41918(0.43) - 2.3631$
#### $= 0.24736$

#### for $n = 2$
#### $E \le \frac{f''(\epsilon(x))}{3!}(x-x_0)(x-x1)(x-x_2)$
#### $\implies E \le \frac{8e^{2\epsilon(x)}}{3!}(x-0)(x-.25)(x-.5)$
#### $\implies E \le \frac{4}{3}e^{2\epsilon(x)}(x)(x-0.25)(x-0.5)$
#### $\implies E \le \frac{4}{3}e^{2(.5)}(x^3 - 0.25x^2 - 0.125x)$
#### $\implies E \le 0.0217$

#### actual error
#### $f(0.43) - 2.363$
#### $= 0.013$

#### 3. Use Neville’s method to obtain the approximations for Lagrange interpolating polynomials of degrees one, two, and three to approximate each of the following: $f (0.43)$ if $f (0) = 1,f (0.25) = 1.64872, f (0.5) = 2.71828, f (0.75) = 4.48169$.

In [8]:
x = np.array([0, 0.25, 0.5, 0.75])
y = np.array([1, 1.64872, 2.71828, 4.48169])
nevilleInterpolation(x, y, 0.43)

array([[1.        , 0.        , 0.        , 0.        ],
       [1.64872   , 2.1157984 , 0.        , 0.        ],
       [2.71828   , 2.4188032 , 2.37638253, 0.        ],
       [4.48169   , 2.2245252 , 2.34886312, 2.36060473]])

#### 4. Neville’s method is used to approximate $f (0.5)$, giving the following table. 
|$x_0=0$|$P_0=0$|||
|:---|:---:|:---:|---:|
|$x_1=0.4$|$P_1=2.8$|$P_{0,1} = 3.5$||
|$x_2=0.7$|$P_2=$|$P_{1,2} = $|$P_{0,1,2} = \frac{22}{7}$|
#### Determine $P_2= f (0.7)$

In [9]:
x = np.array([0 , .4, .7])
y = np.array([1, 1.49182, 1.64872])
nevilleInterpolation(x, y, 0.7)

array([[1.      , 0.      , 0.      ],
       [1.49182 , 1.860685, 0.      ],
       [1.64872 , 1.64872 , 1.64872 ]])

#### 5. Use Eq. (3.10) or Algorithm3.2 to construct interpolating polynomials of degree one, two, and three for the following data. Approximate the specified value using each of the polynomials. $f (0.43)$ if $f (0) = 1, f (0.25) = 1.64872, f (0.5) = 2.71828, f (0.75) = 4.48169$

In [10]:
x = np.array([0, .25, .5, .75])
y = np.array([1, 1.64872, 2.71828, 4.48169])
dividedDifference(x, y)

array([[1.        , 2.59488   , 3.36672   , 2.91210667],
       [1.64872   , 4.27824   , 5.5508    , 0.        ],
       [2.71828   , 7.05364   , 0.        , 0.        ],
       [4.48169   , 0.        , 0.        , 0.        ]])

#### 6. Use Algorithm 3.2 to construct the interpolating polynomial of degree three for the unequally spaced points given in the following table
|$x$|$f(x)$|
|:---|---:|
|$-0.1$|$5.3$|
|$0$|$2$|
|$0.2$|$3.19$|
|$0.3$|$1$|

In [11]:
x = np.array([-0.1, 0])
y = np.array([5.3, 2])
dividedDifference(x, y)

array([[  5.3, -33. ],
       [  2. ,   0. ]])