In [1]:
import numpy as np
import numericalMethods as nm

In [4]:
A = np.array([[3.333, 15920, 10.333, 7953], [2.222, 16.71, 9.612, 0.965], [-1.5611, 5.1792, -1.6855, 2.714]])
nm.GaussianElimination(A)
nm.PartialPivoting(A)
nm.ScaledPartialPivoting(A)

array([ 1. ,  0.5, -1. ])

In [16]:
A = np.array([[2,1,0,0], [-1,3,3,0],[2,-2,1,4],[-2,2,2,5]])
L, U = nm.LUdecomposition(A)
b = np.array([0,5,-2,6]).reshape(4,1)
L = np.hstack((L,b))
nm.ScaledPartialPivoting(L)

array([0.        , 5.        , 2.28571429, 2.08      ])

In [50]:
A = np.array([[1,-2,3,0], [3,-6,9,3],[2,1,4,1],[1,-2,2,-2]])
np.random.shuffle(A)
print(A)
nm.LUdecomposition(A)

[[ 2  1  4  1]
 [ 1 -2  2 -2]
 [ 1 -2  3  0]
 [ 3 -6  9  3]]


(array([[1. , 0. , 0. , 0. ],
        [0.5, 1. , 0. , 0. ],
        [0.5, 1. , 1. , 0. ],
        [1.5, 3. , 3. , 1. ]]),
 array([[ 2. ,  1. ,  4. ,  1. ],
        [ 0. , -2.5,  0. , -2.5],
        [ 0. ,  0. ,  1. ,  2. ],
        [ 0. ,  0. ,  0. ,  3. ]]))

In [19]:
A = np.array([[4,-1,1],[-1,3,0],[1,0,2]])
nm.LDLdecomposition(A)
nm.CholeskyDecomposition(A)

(array([[ 2.        ,  0.        ,  0.        ],
        [-0.5       ,  1.6583124 ,  0.        ],
        [ 0.5       ,  0.15075567,  1.31425748]]),
 array([[ 2.        , -0.5       ,  0.5       ],
        [ 0.        ,  1.6583124 ,  0.15075567],
        [ 0.        ,  0.        ,  1.31425748]]))